### ISSUE TITLE
Bank Reconciliation

### ISSUE THREAD

**Issue by silverio** [europeanplaice/subset_sum#2]
Hi, 

Thanks for this great pkg. I am testing the wasm package (wasm_find_subset) to do reconciliations. But I have some questions:

1.  My subset array and target may include some values with  2 decimal places,  
`example: subset [-40000, 25305.55, 25305.55, 30000, 54123.78] target: 79429.33`.
 Could I just multiply the subset and the target by 100 to remove the decimals and make it work? By doing this will it take longer get a result? 

2.  Using the same subset example as above, sometimes I can have repeated numbers in the subset array. Is it possible to get `wasm_find_subset` to return the result as positions in the array? example:  
`subset [-40000, 25305.55, 25305.55, 30000, 54123.78] target: 79429.33 `
`result:  [[1, 4], [2,4]]`

3. Currently the `wasm_find_subset` function returns a string. Could it return an array of arrays? Or is there an easy way to convert that string to an array of arrays.

**Comment by europeanplaice** [comment]
Hi there. Thank you for opening this issue.

### Q1
> My subset array and target may include some values with 2 decimal places,
> example: subset [-40000, 25305.55, 25305.55, 30000, 54123.78] target: 79429.33.
> Could I just multiply the subset and the target by 100 to remove the decimals and make it work? By doing this will it take longer get a result?

It’s just as you said. You can get the result you desire by multiplying by 100. I think an additional time to compute would not be so long for most situations.

---
### Q2
> Using the same subset example as above, sometimes I can have repeated numbers in the subset array. Is it possible to get wasm_find_subset to return the result as positions in the array? example:
> subset [-40000, 25305.55, 25305.55, 30000, 54123.78] target: 79429.33
> result: [[1, 4], [2,4]]

Currently I haven't implemented such a function. However, it's not impossible to make it, and I'll work on it.

---
### Q3
> Currently the wasm_find_subset function returns a string. Could it return an array of arrays? Or is there an easy way to convert that string to an array of arrays.

This function was made only for https://europeanplaice.github.io/subset_sum/find_subset/ . In this sense, a result of this function needs to be a string type. Inside the function, it converts the array type to string to write html. Unfortunately, you can't easily get an array of arrays from this function. However, as Q2, this is a reasonable request and I'll try to implement it. Thank you.
