### ISSUE TITLE
Importing the rust crate doesn't work

### ISSUE THREAD

**Issue by MhhhxX** [europeanplaice/subset_sum#4]
I would like to use your rust crate in my project but I ran into a problem when I add it to my `Cargo.toml` file.
Running `cargo build` ends up in an error:

```
error[E0433]: failed to resolve: use of undeclared crate or module `mem`
   --> /home/max/.cargo/registry/src/index.crates.io-6f17d22bba15001f/subset_sum-0.22.1/src/dp_module.rs:503:21
    |
503 |                     mem::swap(&mut y.0, &mut y.1);
    |                     ^^^ use of undeclared crate or module `mem`
```

This what I add to my `Cargo.toml`:
```
[dependencies]
dpss = {version = "0.22.1", package = "subset_sum"}
```

**Comment by MhhhxX** [comment]
Importing `version = "0.21.0"` or a below works for me. From version `0.22.0` onwards it's broken.

**Comment by europeanplaice** [comment]
I tried to fix the bug and published a new version as 0.22.2. Can you make sure the new version works?
`dpss = {version = "0.22.2", package = "subset_sum"}`

**Comment by MhhhxX** [comment]
I tested it right now. Now it works.
Thank you for the fix.

**Comment by europeanplaice** [comment]
I wish your project will succeed with my tool.
